// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S$RescriptSchema from "rescript-schema/src/S.bs.js";

var modSchema = S$RescriptSchema.schema(function (s) {
      return {
              Author: s.matches(S$RescriptSchema.string),
              Name: s.matches(S$RescriptSchema.string),
              Folder: s.matches(S$RescriptSchema.string),
              Version: s.matches(S$RescriptSchema.$$null(S$RescriptSchema.string)),
              Description: s.matches(S$RescriptSchema.string),
              UUID: s.matches(S$RescriptSchema.string),
              Created: s.matches(S$RescriptSchema.string),
              Dependencies: s.matches(S$RescriptSchema.array(S$RescriptSchema.string)),
              Group: s.matches(S$RescriptSchema.string)
            };
    });

var schema = S$RescriptSchema.schema(function (s) {
      return {
              Mods: s.matches(S$RescriptSchema.array(modSchema)),
              MD5: s.matches(S$RescriptSchema.string)
            };
    });

function parse(__x) {
  return S$RescriptSchema.parseWith(__x, schema);
}

function make(author, name, folder, version, description, uuid, created, dependencies, group, md5) {
  var mod = {
    Author: author,
    Name: name,
    Folder: folder,
    Version: version,
    Description: description,
    UUID: uuid,
    Created: created,
    Dependencies: dependencies,
    Group: group
  };
  var mods = [mod];
  return {
          Mods: mods,
          MD5: md5
        };
}

function makeWithMods(mods, md5) {
  return {
          Mods: mods,
          MD5: md5
        };
}

export {
  schema ,
  parse ,
  make ,
  makeWithMods ,
}
/* modSchema Not a pure module */
